ServiceHost = "0.0.0.0"
ServicePort = 8080
MinioHost = "localhost"
MinioPort = 9000
MinioAccessKey = "minio"
MinioSecretKey = "minio1234"
MinioBucket = "img"
SecretKey = "secret_key"
ExpiresAtMinutes = "100m"

RedisHost = "localhost"
RedisPort = 6379
RedisUser = ""
RedisPassword = "password123"
RedisDB = 0     
RedisDialTimeoutSec = "10s"
RedisReadTimeoutSec = "10s"
RedisAppPrefix = "app:"

AuthToken = "secret12"